"""
Django settings for SushiBar project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

from django.utils.translation import ugettext_lazy as _
import os
from datetime import timedelta
from corsheaders.defaults import default_headers

SITE_ROOT = os.path.dirname(os.path.realpath(__file__))
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'cvu@5*oeo+=tg3&3ak7shbl^4&1w54@ddy4p1zd7@7s*$8_m6d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
ALLOWED_HOSTS = ['192.168.88.243', 'localhost', '127.0.0.1', '192.168.89.252', 'sushibar.soft21.pl', '192.168.88.248', 'yakitori-grill.pl']
# ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'SushiBar.apps.SuitConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'news.apps.NewsConfig',
    'users.apps.UsersConfig',
    'crispy_forms',
    'contact.apps.ContactConfig',
    'about.apps.AboutConfig',
    'menu.apps.MenuConfig',
    'rest_framework',
    'ckeditor',
    'ckeditor_uploader',
    'django_user_agents',
    #allauth
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'translation_manager',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True # If this is used then `CORS_ORIGIN_WHITELIST` will not have any effect
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list(default_headers) + [
    'Access-Control-Expose-Headers',
    'x-total-count',
    'link'
]

CORS_EXPOSE_HEADERS = [
    'x-total-count',
    'link'
]

MIDDLEWARE_CLASSES = (
    'utils.multilang.middleware.AdminLocaleURLMiddleware',
)


ROOT_URLCONF = 'SushiBar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [(os.path.join(BASE_DIR, 'templates')),], #global template folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.i18n',
                'django.contrib.messages.context_processors.messages',
                'contact.context_processors.bar_informations',
                'contact.context_processors.opening_hours',
                'contact.context_processors.realization_hours',
                'menu.context_processors.user_cart',
                'contact.context_processors.realization_status',
                'contact.context_processors.getRestaurantStatus',
            ],
            'debug': DEBUG,
        },
    },
]

#WSGI_APPLICATION = 'SushiBar.wsgi.application'

AUTH_USER_MODEL = 'users.CustomUser'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAdminUser',
    ],

    'DEFAULT_AUTHENTICATION_CLASSES': [
            'rest_framework_simplejwt.authentication.JWTAuthentication',
            'rest_framework.authentication.SessionAuthentication',

    ],
    'DEFAULT_PAGINATION_CLASS': 'SushiBar.pagepagination.HeaderPageNumberPagination',
    'PAGE_SIZE': 10,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=5),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('JWT',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}
# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
		'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'server751331_psushibar',
        'USER': 'server751331_psushibar',
        'PASSWORD': '3hUvkDoI',
        'HOST': 'pgsql131.server751331.nazwa.pl',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'pl'

ADMIN_LANGUAGE_CODE = 'pl'

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_L10N = True

USE_TZ = False

LANGUAGES = (
    ('pl', _('Polish')),
    ('en', _('English')),
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
#STATIC_ROOT ='/home/jasiu/Publiczny/SushiBar/SushiBar/static'
STATIC_ROOT = os.path.abspath('static')
STATICFILES_DIRS = [
    #os.path.join(BASE_DIR, "static"), #global static folder
	#os.path.abspath('static'),
	#os.path.abspath('static'),
]

LOCALE_PATHS = [
    os.path.abspath('locale'),
]
TRANSLATIONS_PROJECT_BASE_DIR = os.path.abspath('locale')

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MEDIA_ROOT = os.path.join(BASE_DIR,'media') #folder przechowywanych zdjec
MEDIA_URL = '/media/'

CKEDITOR_UPLOAD_PATH = 'about_us/'

CKEDITOR_CONFIGS = {
    'aboutus_ckeditor': {
        'toolbar': 'standard',
        'font_names': 'Exo; Exo Semi Bold; Open Seans; Arial; Times New Roman;',
        'contentsCss': '/static/css/ckeditor.css',
    },
}
LOGIN_URL = 'login' #przekierowanie do strony logowania w przypadku używania dekoratora login_required() (gdy brak autoryzacji)

LOGIN_REDIRECT_URL = 'main' #przekierowanie po udanym logowaniu

#LOGOUT_REDIRECT_URL = 'news:temporary_main'
#konfiguracja poczty
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'server478609.nazwa.pl'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'sushibar@soft21.pl'
EMAIL_HOST_PASSWORD = 'PtHaZew8eOX'
DEFAULT_FROM_EMAIL = 'sushibar@soft21.pl'
SERVER_EMAIL = 'sushibar@soft21.pl'

SITE_ID = 1
ACCOUNT_EMAIL_REQUIRED=True
ACCOUNT_USERNAME_REQURIED=True

ACCOUNT_AUTHENTICATION_METHOD = "email" 
SOCIALACCOUNT_QUERY_EMAIL = ACCOUNT_EMAIL_REQUIRED
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_REQUIRED = False
ACCOUNT_ADAPTER = "users.adapter.MyLoginAccountAdapter"
SOCIALACCOUNT_ADAPTER = 'users.adapter.MySocialAccountAdapter'

P24 = {
    'url': "https://sandbox.przelewy24.pl/api/v1/transaction/",
    'trnRequest': "https://sandbox.przelewy24.pl/trnRequest/",
    'urlReturn': "https://sushibar.soft21.pl/zamowienia?sessionId=",
    'urlStatus': "https://sushibar.soft21.pl/zamowienia?sessionId=",
}
